package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"buma-be/internal/domain"
)

// CommitmentRepository is an autogenerated mock type using mockery pattern
type CommitmentRepository struct {
	mock.Mock
}

func (m *CommitmentRepository) CreateCommitment(ctx context.Context, req domain.CreateCommitmentRequest) (*domain.CollectionCommitment, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) UpdateCommitmentByReason(ctx context.Context, req domain.CreateCommitmentRequest) (*domain.CollectionCommitment, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) CreateOrUpdateCommitment(ctx context.Context, req domain.CreateCommitmentRequest) (*domain.CollectionCommitment, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) GetCommitmentsByAccountNo(ctx context.Context, accountNo string) ([]domain.CollectionCommitment, error) {
	args := m.Called(ctx, accountNo)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) GetCommitmentsByDate(ctx context.Context, date string) ([]domain.CollectionCommitment, error) {
	args := m.Called(ctx, date)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) GetCommitments(ctx context.Context, filter domain.CommitmentFilter) (*domain.PaginatedCommitmentResponse, error) {
	args := m.Called(ctx, filter)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.PaginatedCommitmentResponse), args.Error(1)
}

func (m *CommitmentRepository) GetCommitmentByID(ctx context.Context, id string) (*domain.CollectionCommitment, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.CollectionCommitment), args.Error(1)
}

func (m *CommitmentRepository) UpdateCommitmentByID(ctx context.Context, id string, req domain.UpdateCommitmentRequest) (*domain.CollectionCommitment, error) {
	args := m.Called(ctx, id, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.CollectionCommitment), args.Error(1)
}


