package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"buma-be/internal/domain"
)

// DebtorRepository is an autogenerated mock type using mockery pattern
type DebtorRepository struct {
	mock.Mock
}

func (m *DebtorRepository) GetMonitoringData(ctx context.Context, filter domain.DebtorFilter) (*domain.MonitoringResponse, error) {
	args := m.Called(ctx, filter)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.MonitoringResponse), args.Error(1)
}

func (m *DebtorRepository) GetDebtorByAccountNo(ctx context.Context, accountNo string) (*domain.DebtorAccount, error) {
	args := m.Called(ctx, accountNo)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.DebtorAccount), args.Error(1)
}

func (m *DebtorRepository) GetHighExposureTier1Accounts(ctx context.Context) ([]domain.DebtorAccount, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.DebtorAccount), args.Error(1)
}
