package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"buma-be/internal/domain"
)

// OfficerRepository is an autogenerated mock type using mockery pattern
type OfficerRepository struct {
	mock.Mock
}

func (m *OfficerRepository) CreateOfficer(ctx context.Context, officer domain.Officer) (*domain.Officer, error) {
	args := m.Called(ctx, officer)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.Officer), args.Error(1)
}

func (m *OfficerRepository) GetAllOfficers(ctx context.Context) ([]domain.Officer, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.Officer), args.Error(1)
}

func (m *OfficerRepository) GetOfficerByID(ctx context.Context, officerID string) (*domain.Officer, error) {
	args := m.Called(ctx, officerID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.Officer), args.Error(1)
}
